[package]
name = "Pulsar-Engine"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
ez_logging = "0.1.2"
hey_listen = "0.5.0"
lazy_static = "1.5.0"
pollster = "0.3.0"
thiserror = "1.0.65"
wgpu = "22.1.0"
winit = "0.30.5"

[build-dependencies]
slint-build = "1.7.2"
